### PR TITLE
(issue no: #55) New version of About us section for Chess Js webstie

### PR DESCRIPTION
**Pull request by somesh526**
Tech stacks-**HTML/CSS**
Modified about.html,about.css file
I kept the position of the UI elements as the same but improved the **UI look**(modern website look) by adding boxes
Modified background color, added new fonts
added home icon which redirects to home page
improved team (developers) section look by adding profile cards with hover effect
added hover effect over the social media icons
added a small footer section
completely **responsive**(using CSS flex)
Hope it merged into the main branch.Thank you @ashishpapanai 
Screenshot 2021-01-07 123742

### CODE REVIEW

**Review by ashishpapanai — CHANGES_REQUESTED** [review]
Hi @somesh526 Please make the changes mentioned to you in Slack.

**Comment by somesh526** [comment]
Worked on changes you mentioned and updated status as final commit @ashishpapanai 
Screenshot 2021-01-07 164153

**Review by ashishpapanai — CHANGES_REQUESTED** [review]
Home is highlighted even when the user is in the About Us page. 
Please rectify that. 
SharedScreenshot

**Comment by somesh526** [comment]
Hello, @ashishpapanai  I updated it kindly have a look into it . Thank you

**Review by ashishpapanai — APPROVED** [review]

**Comment by ashishpapanai** [comment]
Please add the issue number to the title.

**Comment by somesh526** [comment]
Thank you so much @ashishpapanai

**Pull request closed without merging**
