### PR TITLE
Issue#64, #65, #66: Created Single Template for GUI, Added Chess Board Themes, Added Help page

### PR DESCRIPTION
**Pull request by drishti307**
1) Implemented a Single-Template-GUI using Flask and Jinja. To run the application, use command _flask run_  #64 
2) Added **Help** page (Content to be added)
3) Added option to **Change Board Colours/Theme** (game restarts on changing theme) #66 
4) Edited and formatted About Us according to flask structure page based on a previous PR. #61 
5) Modularised the code (_flask structure_), and changed the image paths
         - Templates folder contains all HTML files
         - Static Folder contains Images, CSS files, and js files.
6) Tips are displayed on hovering over buttons #65

### CODE REVIEW

**Review by ashishpapanai — CHANGES_REQUESTED** [review]
Hi @drishti307,
I am suggesting a few changes: 

1. Decrease the opacity of the navbar. 
2. Invalid FEN Still turns the page unresponsive. 
3. No tip is displayed while hovering over resign button 
4. Please refrain from restarting the game on changing the colour theme of the board. 
5. Please prepare a dependencies list or create an issue for updating the readme and contributing guidelines as the complete structure of the code is changed and other contributors need to know how to clone and run the repo locally and the requirements to run it.  

Rest all changes are spot on and amazing.

**Comment by anshuman9999** [comment]
@drishti307  Please check that the game should not restart when changing the board color

**Comment by drishti307** [comment]
Alright, I'll make these changes.

**Comment by drishti307** [comment]
I have made the changes, please review those. 
1. FEN to be done, creating a separate issue for the same.
2. _The opacity of the navbar might not be very apparent because the background is black_
3. 3,4,5 implemented

**Comment by ashishpapanai** [comment]
@drishti307  Suggested a few errors on Slack, Please have a look at them.

**Review by ashishpapanai — CHANGES_REQUESTED** [review]
Please keep a separate section for the footer considering the responsiveness of the website.
SharedScreenshot2

The Footer text is overlapping the Engine output on mobile devices.
Screenshot (675)

**Comment by drishti307** [comment]
Shifted the footer down and made it responsive.

**Review by ashishpapanai — CHANGES_REQUESTED** [review]
Final changes to the footer, mentioned in slack. Please have a look and try to work on them @drishti307.

**Comment by drishti307** [comment]
Removed the Footer

**Comment by anshuman9999** [comment]
@drishti307 The Home link in the navbar is always highlighted, doesn't matter which page the user is on. Please fix this.

**Review by ashishpapanai — CHANGES_REQUESTED** [review]
Please fix the Navbar highlighting issue.

**Comment by drishti307** [comment]
I believe somebody has already created a PR for this, so it should be resolved when you merge that. PR #68

**Comment by ashishpapanai** [comment]
@drishti307 please gitignore pycache.

**Pull request merged**
