### PR TITLE
Edited gui.js and styles.css

### PR DESCRIPTION
**Pull request by crmsnbleyd**
- Fixed floating "resign" button
- Added code to dynamically change background size when resizing the window to gui.js (zoom must be less than 130; did not modify that since it was already working)

### CODE REVIEW

**Review by anshuman9999 — CHANGES_REQUESTED** [review]
@crmsnbleyd  I don't think there is a need to change the background image size. Just remove the code for that and your PR will be merged. Thanks.

**Comment by crmsnbleyd** [comment]
image

I added the resizing because without it, the website can look like this on 100% zoom.   
## With resizing:
image  
Would you like me to try doing the same in CSS? I tried that at first and it didn't work but I'm sure one could do it somehow.

**Comment by anshuman9999** [comment]
@crmsnbleyd actually after your changes, the site has big white borders for ipad and ipad pro. Please test it in your browser's dev tools with your changes.

**Comment by crmsnbleyd** [comment]
image
The exact same code is showing different results on Chrome and Firefox's IPad model. I had not caught this because I'd been developing on Firefox. The function is not firing at all in chrome and i have no idea why. I'll update this thread once i have an answer.

**Comment by ashishpapanai** [comment]
Hello @crmsnbleyd The changes suggested by you are causing white border for the Laptops with 14inch screen size and Tablet devices with not so common resolutions. It would be great if you could fix that issue.

**Review by ashishpapanai — CHANGES_REQUESTED** [review]
Please refrain from using `var`. The project is intended to give preference to `let` over `var`.

**Review by ashishpapanai — APPROVED** [review]

**Pull request closed without merging**
